/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 18:28:29 UTC)
 * on 2015-08-02 at 18:26:23 UTC 
 * Modify at your own risk.
 */

package com.appspot.omega_bearing_780.scores;

/**
 * Service definition for Scores (v1).
 *
 * <p>
 * Score Minion API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ScoresRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Scores extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.20.0 of the scores library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://omega-bearing-780.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "scores/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Scores(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Scores(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Exposes an API endpoint to query for scores for the current user. Args: request: An instance of
   * ScoresListRequest parsed from the API request. Returns: An instance of ScoresListResponse
   * containing the scores for the current user returned in the query. If the API request specifies an
   * order of WHEN (the default), the results are ordered by time from most recent to least recent. If
   * the API request specifies an order of TEXT, the results are ordered by the string value of the
   * scores.
   *
   * Create a request for the method "getGameInfo".
   *
   * This request holds the parameters needed by the scores server.  After setting any optional
   * parameters, call the {@link GetGameInfo#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetGameInfo getGameInfo() throws java.io.IOException {
    GetGameInfo result = new GetGameInfo();
    initialize(result);
    return result;
  }

  public class GetGameInfo extends ScoresRequest<com.appspot.omega_bearing_780.scores.model.ScoresMessagesGameInfoResponse> {

    private static final String REST_PATH = "game";

    /**
     * Exposes an API endpoint to query for scores for the current user. Args: request: An instance of
     * ScoresListRequest parsed from the API request. Returns: An instance of ScoresListResponse
     * containing the scores for the current user returned in the query. If the API request specifies
     * an order of WHEN (the default), the results are ordered by time from most recent to least
     * recent. If the API request specifies an order of TEXT, the results are ordered by the string
     * value of the scores.
     *
     * Create a request for the method "getGameInfo".
     *
     * This request holds the parameters needed by the the scores server.  After setting any optional
     * parameters, call the {@link GetGameInfo#execute()} method to invoke the remote operation. <p>
     * {@link
     * GetGameInfo#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetGameInfo() {
      super(Scores.this, "GET", REST_PATH, null, com.appspot.omega_bearing_780.scores.model.ScoresMessagesGameInfoResponse.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetGameInfo setAlt(java.lang.String alt) {
      return (GetGameInfo) super.setAlt(alt);
    }

    @Override
    public GetGameInfo setFields(java.lang.String fields) {
      return (GetGameInfo) super.setFields(fields);
    }

    @Override
    public GetGameInfo setKey(java.lang.String key) {
      return (GetGameInfo) super.setKey(key);
    }

    @Override
    public GetGameInfo setOauthToken(java.lang.String oauthToken) {
      return (GetGameInfo) super.setOauthToken(oauthToken);
    }

    @Override
    public GetGameInfo setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetGameInfo) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetGameInfo setQuotaUser(java.lang.String quotaUser) {
      return (GetGameInfo) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetGameInfo setUserIp(java.lang.String userIp) {
      return (GetGameInfo) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key("game_id_str")
    private java.lang.String gameIdStr;

    /**

     */
    public java.lang.String getGameIdStr() {
      return gameIdStr;
    }

    public GetGameInfo setGameIdStr(java.lang.String gameIdStr) {
      this.gameIdStr = gameIdStr;
      return this;
    }

    @com.google.api.client.util.Key("max_num_sources")
    private java.lang.Long maxNumSources;

    /**

     */
    public java.lang.Long getMaxNumSources() {
      return maxNumSources;
    }

    public GetGameInfo setMaxNumSources(java.lang.Long maxNumSources) {
      this.maxNumSources = maxNumSources;
      return this;
    }

    @Override
    public GetGameInfo set(String parameterName, Object value) {
      return (GetGameInfo) super.set(parameterName, value);
    }
  }

  /**
   * Exposes an API endpoint to retrieve the scores of multiple games. Can be reference on dev server
   * by using the following URL: http://localhost:8080/_ah/api/scores/v1/all_games Args: request: An
   * instance of GamesRequest parsed from the API request. Returns: An instance of GamesResponse with
   * the set of known games matching the request parameters.
   *
   * Create a request for the method "getGames".
   *
   * This request holds the parameters needed by the scores server.  After setting any optional
   * parameters, call the {@link GetGames#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetGames getGames() throws java.io.IOException {
    GetGames result = new GetGames();
    initialize(result);
    return result;
  }

  public class GetGames extends ScoresRequest<com.appspot.omega_bearing_780.scores.model.ScoresMessagesGamesResponse> {

    private static final String REST_PATH = "all_games";

    /**
     * Exposes an API endpoint to retrieve the scores of multiple games. Can be reference on dev
     * server by using the following URL: http://localhost:8080/_ah/api/scores/v1/all_games Args:
     * request: An instance of GamesRequest parsed from the API request. Returns: An instance of
     * GamesResponse with the set of known games matching the request parameters.
     *
     * Create a request for the method "getGames".
     *
     * This request holds the parameters needed by the the scores server.  After setting any optional
     * parameters, call the {@link GetGames#execute()} method to invoke the remote operation. <p>
     * {@link
     * GetGames#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetGames() {
      super(Scores.this, "GET", REST_PATH, null, com.appspot.omega_bearing_780.scores.model.ScoresMessagesGamesResponse.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetGames setAlt(java.lang.String alt) {
      return (GetGames) super.setAlt(alt);
    }

    @Override
    public GetGames setFields(java.lang.String fields) {
      return (GetGames) super.setFields(fields);
    }

    @Override
    public GetGames setKey(java.lang.String key) {
      return (GetGames) super.setKey(key);
    }

    @Override
    public GetGames setOauthToken(java.lang.String oauthToken) {
      return (GetGames) super.setOauthToken(oauthToken);
    }

    @Override
    public GetGames setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetGames) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetGames setQuotaUser(java.lang.String quotaUser) {
      return (GetGames) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetGames setUserIp(java.lang.String userIp) {
      return (GetGames) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long count;

    /**

     */
    public java.lang.Long getCount() {
      return count;
    }

    public GetGames setCount(java.lang.Long count) {
      this.count = count;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String division;

    /**

     */
    public java.lang.String getDivision() {
      return division;
    }

    public GetGames setDivision(java.lang.String division) {
      this.division = division;
      return this;
    }

    @com.google.api.client.util.Key("team_id.twitter_account.user_defined_name")
    private java.lang.String teamIdTwitterAccountUserDefinedName;

    /**

     */
    public java.lang.String getTeamIdTwitterAccountUserDefinedName() {
      return teamIdTwitterAccountUserDefinedName;
    }

    public GetGames setTeamIdTwitterAccountUserDefinedName(java.lang.String teamIdTwitterAccountUserDefinedName) {
      this.teamIdTwitterAccountUserDefinedName = teamIdTwitterAccountUserDefinedName;
      return this;
    }

    @com.google.api.client.util.Key("pagination_token")
    private java.lang.String paginationToken;

    /**

     */
    public java.lang.String getPaginationToken() {
      return paginationToken;
    }

    public GetGames setPaginationToken(java.lang.String paginationToken) {
      this.paginationToken = paginationToken;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String league;

    /**

     */
    public java.lang.String getLeague() {
      return league;
    }

    public GetGames setLeague(java.lang.String league) {
      this.league = league;
      return this;
    }

    @com.google.api.client.util.Key("team_id.twitter_account.profile_image_url_https")
    private java.lang.String teamIdTwitterAccountProfileImageUrlHttps;

    /**

     */
    public java.lang.String getTeamIdTwitterAccountProfileImageUrlHttps() {
      return teamIdTwitterAccountProfileImageUrlHttps;
    }

    public GetGames setTeamIdTwitterAccountProfileImageUrlHttps(java.lang.String teamIdTwitterAccountProfileImageUrlHttps) {
      this.teamIdTwitterAccountProfileImageUrlHttps = teamIdTwitterAccountProfileImageUrlHttps;
      return this;
    }

    @com.google.api.client.util.Key("max_game_time_start_utc_secs")
    private java.lang.Long maxGameTimeStartUtcSecs;

    /**

     */
    public java.lang.Long getMaxGameTimeStartUtcSecs() {
      return maxGameTimeStartUtcSecs;
    }

    public GetGames setMaxGameTimeStartUtcSecs(java.lang.Long maxGameTimeStartUtcSecs) {
      this.maxGameTimeStartUtcSecs = maxGameTimeStartUtcSecs;
      return this;
    }

    @com.google.api.client.util.Key("team_id.twitter_account.id_str")
    private java.lang.String teamIdTwitterAccountIdStr;

    /**

     */
    public java.lang.String getTeamIdTwitterAccountIdStr() {
      return teamIdTwitterAccountIdStr;
    }

    public GetGames setTeamIdTwitterAccountIdStr(java.lang.String teamIdTwitterAccountIdStr) {
      this.teamIdTwitterAccountIdStr = teamIdTwitterAccountIdStr;
      return this;
    }

    @com.google.api.client.util.Key("min_game_time_start_utc_secs")
    private java.lang.Long minGameTimeStartUtcSecs;

    /**

     */
    public java.lang.Long getMinGameTimeStartUtcSecs() {
      return minGameTimeStartUtcSecs;
    }

    public GetGames setMinGameTimeStartUtcSecs(java.lang.Long minGameTimeStartUtcSecs) {
      this.minGameTimeStartUtcSecs = minGameTimeStartUtcSecs;
      return this;
    }

    @com.google.api.client.util.Key("team_id.score_reporter_id")
    private java.lang.String teamIdScoreReporterId;

    /**

     */
    public java.lang.String getTeamIdScoreReporterId() {
      return teamIdScoreReporterId;
    }

    public GetGames setTeamIdScoreReporterId(java.lang.String teamIdScoreReporterId) {
      this.teamIdScoreReporterId = teamIdScoreReporterId;
      return this;
    }

    @com.google.api.client.util.Key("age_bracket")
    private java.lang.String ageBracket;

    /**

     */
    public java.lang.String getAgeBracket() {
      return ageBracket;
    }

    public GetGames setAgeBracket(java.lang.String ageBracket) {
      this.ageBracket = ageBracket;
      return this;
    }

    @com.google.api.client.util.Key("tournament_id")
    private java.lang.String tournamentId;

    /**

     */
    public java.lang.String getTournamentId() {
      return tournamentId;
    }

    public GetGames setTournamentId(java.lang.String tournamentId) {
      this.tournamentId = tournamentId;
      return this;
    }

    @com.google.api.client.util.Key("team_id.twitter_account.screen_name")
    private java.lang.String teamIdTwitterAccountScreenName;

    /**

     */
    public java.lang.String getTeamIdTwitterAccountScreenName() {
      return teamIdTwitterAccountScreenName;
    }

    public GetGames setTeamIdTwitterAccountScreenName(java.lang.String teamIdTwitterAccountScreenName) {
      this.teamIdTwitterAccountScreenName = teamIdTwitterAccountScreenName;
      return this;
    }

    @Override
    public GetGames set(String parameterName, Object value) {
      return (GetGames) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Scores}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Scores}. */
    @Override
    public Scores build() {
      return new Scores(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ScoresRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setScoresRequestInitializer(
        ScoresRequestInitializer scoresRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(scoresRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
