/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-27 at 21:33:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.omega_bearing_780.scores.model;

/**
 * Response with detailed info about a game.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the scores. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ScoresMessagesGameInfoResponse extends com.google.api.client.json.GenericJson {

  /**
   * Source of latest model update to game.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("score_reporter_source")
  private ScoresMessagesGameSource scoreReporterSource;

  /**
   * Source of latest model update to game.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("twitter_sources")
  private java.util.List<ScoresMessagesGameSource> twitterSources;

  static {
    // hack to force ProGuard to consider ScoresMessagesGameSource used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(ScoresMessagesGameSource.class);
  }

  /**
   * Source of latest model update to game.
   * @return value or {@code null} for none
   */
  public ScoresMessagesGameSource getScoreReporterSource() {
    return scoreReporterSource;
  }

  /**
   * Source of latest model update to game.
   * @param scoreReporterSource scoreReporterSource or {@code null} for none
   */
  public ScoresMessagesGameInfoResponse setScoreReporterSource(ScoresMessagesGameSource scoreReporterSource) {
    this.scoreReporterSource = scoreReporterSource;
    return this;
  }

  /**
   * Source of latest model update to game.
   * @return value or {@code null} for none
   */
  public java.util.List<ScoresMessagesGameSource> getTwitterSources() {
    return twitterSources;
  }

  /**
   * Source of latest model update to game.
   * @param twitterSources twitterSources or {@code null} for none
   */
  public ScoresMessagesGameInfoResponse setTwitterSources(java.util.List<ScoresMessagesGameSource> twitterSources) {
    this.twitterSources = twitterSources;
    return this;
  }

  @Override
  public ScoresMessagesGameInfoResponse set(String fieldName, Object value) {
    return (ScoresMessagesGameInfoResponse) super.set(fieldName, value);
  }

  @Override
  public ScoresMessagesGameInfoResponse clone() {
    return (ScoresMessagesGameInfoResponse) super.clone();
  }

}
