/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-07-16 18:28:29 UTC)
 * on 2015-08-02 at 18:26:23 UTC 
 * Modify at your own risk.
 */

package com.appspot.omega_bearing_780.scores.model;

/**
 * Source of latest model update to game.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the scores. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ScoresMessagesGameSource extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("score_reporter_url")
  private java.lang.String scoreReporterUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("tweet_text")
  private java.lang.String tweetText;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("twitter_account")
  private ScoresMessagesTwitterAccount twitterAccount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("update_time_utc_str")
  private java.lang.String updateTimeUtcStr;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getScoreReporterUrl() {
    return scoreReporterUrl;
  }

  /**
   * @param scoreReporterUrl scoreReporterUrl or {@code null} for none
   */
  public ScoresMessagesGameSource setScoreReporterUrl(java.lang.String scoreReporterUrl) {
    this.scoreReporterUrl = scoreReporterUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTweetText() {
    return tweetText;
  }

  /**
   * @param tweetText tweetText or {@code null} for none
   */
  public ScoresMessagesGameSource setTweetText(java.lang.String tweetText) {
    this.tweetText = tweetText;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ScoresMessagesTwitterAccount getTwitterAccount() {
    return twitterAccount;
  }

  /**
   * @param twitterAccount twitterAccount or {@code null} for none
   */
  public ScoresMessagesGameSource setTwitterAccount(ScoresMessagesTwitterAccount twitterAccount) {
    this.twitterAccount = twitterAccount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * @param type type or {@code null} for none
   */
  public ScoresMessagesGameSource setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUpdateTimeUtcStr() {
    return updateTimeUtcStr;
  }

  /**
   * @param updateTimeUtcStr updateTimeUtcStr or {@code null} for none
   */
  public ScoresMessagesGameSource setUpdateTimeUtcStr(java.lang.String updateTimeUtcStr) {
    this.updateTimeUtcStr = updateTimeUtcStr;
    return this;
  }

  @Override
  public ScoresMessagesGameSource set(String fieldName, Object value) {
    return (ScoresMessagesGameSource) super.set(fieldName, value);
  }

  @Override
  public ScoresMessagesGameSource clone() {
    return (ScoresMessagesGameSource) super.clone();
  }

}
