/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-15 at 20:10:54 UTC 
 * Modify at your own risk.
 */

package com.appspot.omega_bearing_780.scores.model;

/**
 * Model definition for ScoresMessagesTwitterAccount.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the scores. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ScoresMessagesTwitterAccount extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("id_str")
  private java.lang.String idStr;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("profile_image_url_https")
  private java.lang.String profileImageUrlHttps;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("screen_name")
  private java.lang.String screenName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_defined_name")
  private java.lang.String userDefinedName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdStr() {
    return idStr;
  }

  /**
   * @param idStr idStr or {@code null} for none
   */
  public ScoresMessagesTwitterAccount setIdStr(java.lang.String idStr) {
    this.idStr = idStr;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileImageUrlHttps() {
    return profileImageUrlHttps;
  }

  /**
   * @param profileImageUrlHttps profileImageUrlHttps or {@code null} for none
   */
  public ScoresMessagesTwitterAccount setProfileImageUrlHttps(java.lang.String profileImageUrlHttps) {
    this.profileImageUrlHttps = profileImageUrlHttps;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getScreenName() {
    return screenName;
  }

  /**
   * @param screenName screenName or {@code null} for none
   */
  public ScoresMessagesTwitterAccount setScreenName(java.lang.String screenName) {
    this.screenName = screenName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserDefinedName() {
    return userDefinedName;
  }

  /**
   * @param userDefinedName userDefinedName or {@code null} for none
   */
  public ScoresMessagesTwitterAccount setUserDefinedName(java.lang.String userDefinedName) {
    this.userDefinedName = userDefinedName;
    return this;
  }

  @Override
  public ScoresMessagesTwitterAccount set(String fieldName, Object value) {
    return (ScoresMessagesTwitterAccount) super.set(fieldName, value);
  }

  @Override
  public ScoresMessagesTwitterAccount clone() {
    return (ScoresMessagesTwitterAccount) super.clone();
  }

}
