/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-15 at 20:10:54 UTC 
 * Modify at your own risk.
 */

package com.appspot.omega_bearing_780.scores.model;

/**
 * Response for GetGames.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the scores. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ScoresMessagesGamesResponse extends com.google.api.client.json.GenericJson {

  /**
   * Information to represent a game.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ScoresMessagesGame> games;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("pagination_token")
  private java.lang.String paginationToken;

  /**
   * Information to represent a game.
   * @return value or {@code null} for none
   */
  public java.util.List<ScoresMessagesGame> getGames() {
    return games;
  }

  /**
   * Information to represent a game.
   * @param games games or {@code null} for none
   */
  public ScoresMessagesGamesResponse setGames(java.util.List<ScoresMessagesGame> games) {
    this.games = games;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPaginationToken() {
    return paginationToken;
  }

  /**
   * @param paginationToken paginationToken or {@code null} for none
   */
  public ScoresMessagesGamesResponse setPaginationToken(java.lang.String paginationToken) {
    this.paginationToken = paginationToken;
    return this;
  }

  @Override
  public ScoresMessagesGamesResponse set(String fieldName, Object value) {
    return (ScoresMessagesGamesResponse) super.set(fieldName, value);
  }

  @Override
  public ScoresMessagesGamesResponse clone() {
    return (ScoresMessagesGamesResponse) super.clone();
  }

}
